name: deploy-landing
on:
    push:
        branches:
            - develop

jobs:
    deploy-landing:
        name: Deploy Landing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.LEMON_BOT_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'

            - name: Get Yarn cache path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ${{ steps.yarn-cache-dir-path.outputs.dir }}
                      node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              if: steps.cache-dependencies.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Deploy Landing
              env:
                  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
                  DEV_DISTRIBUTION_ID: ${{ secrets.DEV_DISTRIBUTION_ID }}
                  PROD_DISTRIBUTION_ID: ${{ secrets.PROD_DISTRIBUTION_ID }}
              run: |
                  chmod +x scripts/deploy-landing.sh
                  yarn landing:deploy:prod
